### ISSUE TITLE
abstrahiere parametrized weiter

### ISSUE THREAD

**Issue by joshinils** [joshinils/erinner_bot#1]
https://github.com/joshinils/erinner_bot/blob/65e2607b98aee129b0d0fbb8df21ffad46b7b540/test_erinnerung.py#L96-L123

kann man diese parametrized liste einfacher gestalten? das weiter abstrahieren?
kann man diese liste an tuples generieren und verändern und dann als argument an parametrized weitergeben?

ist das eine gute idee?

**Comment by philsupertramp** [comment]
Nicht ohne den vollständigen Test :stuck_out_tongue_winking_eye: 

Zunächst würde ich mir die Frage stellen:
Was soll mein Test testen?

Parsen einer Zeiteinheit, mit dem Prefix der Eingabe `a in`, aka wieso den extra Aufwand wenns eh überall gleich ist?
```python
@pytest.mark.parametrize("test_input",
                         [
                             (["5"]),
                             (["5m"]),
                             (["5 m"]),
                             (["5min"]),
                             (["5 min"]),
                             (["5:0"]),
                             (["5:0m"]),
                             (["5:0 m"]),
                             (["5:0min"]),
                             (["5:00 min"]),
                             (["5:00"]),
                             (["5:00m"]),
                             (["5:00 m"]),
                             (["5:00min"]),
                             (["5:00 min"]),
                             (["5.0"]),
                             (["5.0m"]),
                             (["5.0 m"]),
                             (["5.0min"]),
                             (["min"]),
                             (["5,0"]),
                             (["5,0m"]),
                             (["5,0 m"]),
                             (["5,0min"]),
                             (["5,0 min"]),
                         ])
def test_in_5_min(test_input):
    e1 = erinnerung(['a', 'in', test_input])

    now = datetime.datetime.now()
    now_plus_5 = now + timedelta(minutes=5)

    seconds_error = (e1.date_due - now_plus_5).total_seconds()
    assert abs(seconds_error) < 1
```

Jetzt mal mit Produkten aus zwei Listen, weil ich keinen Bock hab das so oft zu schreiben:
```python
@pytest.mark.parametrize("test_input", [''.join(i) for i in itertools.product(["5:0", "5:00", "5", "5,0", ""], ["m", "min", " m", " min", ""])])
def test_in_5_min(test_input):
    e1 = erinnerung(['a', 'in', test_input])

    now = datetime.datetime.now()
    now_plus_5 = now + timedelta(minutes=5)

    seconds_error = (e1.date_due - now_plus_5).total_seconds()
    assert abs(seconds_error) < 1
```
und wenn  du keinen Bock auf das rumbasteln mit strings hast kannst dus natürlich auch als 2 parameter übergeben:
```python
@pytest.mark.parametrize("minutes", "time_unit", itertools.product(["5:0", "5:00", "5", "5,0", ""], ["m", "min", " m", " min", ""]))
def test_in_5_min(minutes, time_unit):
    e1 = erinnerung(['a', 'in', f'{minutes}{time_unit}'])

    now = datetime.datetime.now()
    now_plus_5 = now + timedelta(minutes=5)

    seconds_error = (e1.date_due - now_plus_5).total_seconds()
    assert abs(seconds_error) < 1
```
Schade, dass du LinA nicht im neuen Studiengang hattest, die machen super viel Python und da nutzt man diese ganzen `intertools` und `functools` Methoden.
Bevor ich den Abstraktionsschritt zu `itertools` mache, überlege ich vorher aber **immer** ob es nicht besser wäre es so zu lassen wie es ist, da es in Zukunft schwer sein könnte zu verstehen was passiert. Hier ists aber sehr offensichtlich, wir haben 2 listen und bilden deren elementweise produkte, erhalten also am ende eine Liste mit allen möglichen Elementen, das was wir wollen.
Wenn wir jetzt noch verbose im test sagen würden
```python
def test_in_5_min_permutations(test_input):
```
oder irgendwas das nur darauf hinweist, dass wir hier alle möglichen Formen von "5 min" testen, wäre der Kontext reichlich geklärt und ich würde den Test genauso schreiben.

Hoffe das hilft ein wenig.

Ein Kommentare noch:
Wenn du `list` anstatt `typing.List` als type hint nimmst, nimmst du eigentlich ein mutable für den type hint. Das ist mehr als falsch, aber Python akzeptiert es trotzdem.
Nur elemente aus `typing` und die davon erbenden sollten als typehint benutzt werden.

**Comment by joshinils** [comment]
@philsupertramp DANKE!
